In [23]:
# Confusion Matrix
import pandas as pd
import numpy as np
import ast
import json
from operator import add 
from operator import truediv
import re
# import swifter
from tqdm import tqdm

In [24]:
df_cm = pd.read_csv("Dataset/Output/Tagged - Sheet1.csv")

In [25]:
df_cm.head()

,id,summaries,Technology,exact_matched_patt,Actual,Unnamed: 5,Unnamed: 6,Unnamed: 7,Actual(NER)
0,Dn4hgsVR5fA4BkRuFQijKA_0000,Experienced Assistant Manager with a demonstra...,"['Manage', 'eManage', 'Microsoft Excel', 'Micr...","['Manager', 'Microsoft Excel', 'Microsoft Word']","['Manager','Matlab','Microsoft Excel','Microso...",NaN,NaN,NaN,[]
1,F3KRzgtONdkcLHebtHacGg_0000,"psp reconciliation -monthly, weekly and daily ...",bob,[],NaN,NaN,NaN,NaN,[]
2,3MgG7hvahUvsBaMBRhcwTg_0000,Owner at CL Motorsports,C,[],CL Motorsports,NaN,NaN,NaN,[]
3,KfD3AOGALhGBm2gQhSDysg_0000,Additional General Manager at Surat Special Ec...,"['Manage', 'eManage', 'Manager']",['Manager'],Manager,NaN,NaN,NaN,[]
4,DjB2JIolndrvMoyz37yV7Q_0000,"Co-Owner at Longfellow Family, LLC",C,[],"Longfellow Family, LLC",NaN,NaN,NaN,"Longfellow Family, LLC"

In [26]:
for i in range(0, len(df_cm)):
    
    if df_cm["exact_matched_patt"][i][0] == '[':
        
        res = ast.literal_eval(df_cm["exact_matched_patt"][i])
        df_cm["exact_matched_patt"][i] = res
        
    else:
        x = []
        x.insert(0, df_cm["exact_matched_patt"][i])
        df_cm["exact_matched_patt"][i] = x

/Users/shubhamsunwalka/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
for i in range(0, len(df_cm)):
    print(i)
    if df_cm["Actual"][i] is not np.nan:
        
        if df_cm["Actual"][i][0] == '[':
            res = ast.literal_eval(df_cm["Actual"][i])
            df_cm["Actual"][i] = res
            
        else:
            y = []
            y.insert(0, df_cm["Actual"][i])
            df_cm["Actual"][i] = y
        
        
    else:
        
        df_cm["Actual"][i] = '[]'

        if df_cm["Actual"][i][0] == '[':
            res = ast.literal_eval(df_cm["Actual"][i])
            df_cm["Actual"][i] = res
            
        else:
            y = []
            y.insert(0, df_cm["Actual"][i])
            df_cm["Actual"][i] = y

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124

/Users/shubhamsunwalka/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/shubhamsunwalka/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/shubhamsunwalka/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/shubhamsunwalka/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [28]:
# TP: present in both sheet i==j
# TN: not in both (insignificant)
# FP: in extracted sheet but not in manual tagging     i!=j
# FN: in manual tagging and is not in extracted tagging j

In [29]:
tp = []
tn = []
fp = []
fn = []

In [30]:
TP = TN = FP = FN = 0

In [31]:
for ind in df_cm.index:
    TP = FP = 0
    print(i)
    
    for i in range(0, len(df_cm["exact_matched_patt"][ind])):
        
        if df_cm["exact_matched_patt"][ind][i] in df_cm["Actual"][ind]:
            print("\n TP Entries", df_cm["exact_matched_patt"][ind][i])
            print("index",i)
            
            TP = TP + 1
            
                
        else:
            print("No TP/FP")
                
    tp.append(TP)

    
# import numpy as np
# list_1 = ["a", "b", "c", "d", "e"]
# list_2 = ["a", "f", "c", "m"] 
for ind in df_cm.index:
    
    main_list = np.setdiff1d(df_cm["exact_matched_patt"][ind],df_cm["Actual"][ind])
    fp.append(len(main_list))
# # yields the elements in `list_2` that are NOT in `list_1`
    


    
    
# ORIGINAL CODE:

# for ind in df_cm.index:
#     TP = FP = 0
#     print(i)
    
#     for i in range(0, len(df_cm["exact_matched_patt"][ind])):
        
#         if df_cm["exact_matched_patt"][ind][i] in df_cm["Actual"][ind]:
#             print("\n TP Entries", df_cm["exact_matched_patt"][ind][i])
#             print("index",i)
            
#             TP = TP + 1
            
#         elif df_cm["exact_matched_patt"][ind][i] not in df_cm["Actual"][ind] == True:
#             print("\n FP Entries", df_cm["exact_matched_patt"][ind][i])
            
#             FP = FP + 1
                
#         else:
#             print("No TP/FP")
                
#     tp.append(TP)
#     fp.append(FP)

124

 TP Entries Manager
index 0

 TP Entries Microsoft Excel
index 1

 TP Entries Microsoft Word
index 2
2
2
2

 TP Entries Manager
index 0
0
0
0

 TP Entries Manager
index 0
0

 TP Entries COMIT
index 0
0
No TP/FP
0
0
0
0
0
0

 TP Entries Manager
index 0
No TP/FP
1

 TP Entries Manager
index 0
0
0
0

 TP Entries Manager
index 0
0
0
0
0
0
0
0
0

 TP Entries Manager
index 0
0

 TP Entries Manager
index 0
0
0
0
0
0
0

 TP Entries Manager
index 0
0
0
0

 TP Entries Structural
index 0

 TP Entries Create
index 1
1
1
1
1

 TP Entries Manager
index 0

 TP Entries Industry
index 1
1

 TP Entries Manager
index 0
0
0

 TP Entries Manager
index 0
0
0
0
0
0

 TP Entries Chef
index 0
0
0
0

 TP Entries Manager
index 0
0
0
0

 TP Entries Manager
index 0
0

 TP Entries HR Manager
index 0
0
0
0
No TP/FP
0
0
0

 TP Entries Box
index 0

 TP Entries Control
index 1
1
1

 TP Entries Manager
index 0
0
0
0
0
0
0

 TP Entries Manager
index 0
0
0
0
0

 TP Entries Majestic
index 0

 TP Entries pocket
index 1
1
1

 TP Entries i
index 0
0
0
0
0
0

 TP Entries Manager
index 0
0
0
0
0

 TP Entries Manager
index 0
0
0
0
No TP/FP
0
0
0
0
0

 TP Entries Manager
index 0
0
0

 TP Entries Control
index 0

 TP Entries Manager
index 1
1
1

 TP Entries Service
index 0
0
0

 TP Entries Manager
index 0
0
0
0
0
0
No TP/FP
No TP/FP
1
1

 TP Entries Manager
index 0
0
0

 TP Entries Manager
index 0
0
No TP/FP
0

 TP Entries Manager
index 0
0
0
0
0
0
0
0
0

 TP Entries Manager
index 0
0
0

 TP Entries Manager
index 0
0
0
0
0
0
No TP/FP

In [32]:
# import numpy as np
# list_1 = ["a", "b", "c", "d", "e"]
# list_2 = ["a", "f", "c", "m"] 
# main_list = np.setdiff1d(list_2,list_1)
# # yields the elements in `list_2` that are NOT in `list_1`

In [33]:
for ind in df_cm.index:
    
    main_list = np.setdiff1d(df_cm["Actual"][ind], df_cm["exact_matched_patt"][ind])
    fn.append(len(main_list))


# for ind in df_cm.index:
    
#     TP = FN = 0
    
#     for i in range(0, len(df_cm["Actual"][ind])):
        
#         if df_cm["Actual"][ind][i] not in df_cm["exact_matched_patt"][ind] == True:
#             print("\n Actual Entry", df_cm["Actual"][ind][i])
            
#             FN = FN + 1
            
#         else:
            
#             print("FN done")

#     fn.append(FN)

In [34]:
print(len(tp), len(fp), len(fn))

125 125 125

In [35]:
df_matrix = pd.DataFrame(list(zip(tp, fp, fn)), 
               columns =['TP', 'FP', "FN"])
df_matrix.head(-1)

     TP  FP  FN
0     3   0   1
1     0   0   0
2     0   0   1
3     1   0   0
4     0   0   1
..   ..  ..  ..
119   1   0   0
120   0   0   1
121   0   0   2
122   0   0   0
123   0   0   1

[124 rows x 3 columns]

In [36]:
def get_precision(tp,fp):
    
    if tp+fp ==0:
        precision = 0
    else:
        precision = tp/(tp+fp)
    
    return precision

In [37]:
def get_recall(tp,fn):
    
    if tp+fn ==0:
        recall = 0
    else:
        recall = tp/(tp+fn)
    
    return recall

In [38]:
df_matrix['Precision'] = df_matrix.apply(lambda x: get_precision(x["TP"], x["FP"]), axis = 1)

In [39]:
df_matrix["Recall"] = df_matrix.apply(lambda x: get_recall(x["TP"], x["FN"]), axis = 1)

In [40]:
df_matrix.head()

   TP  FP  FN  Precision  Recall
0   3   0   1        1.0    0.75
1   0   0   0        0.0    0.00
2   0   0   1        0.0    0.00
3   1   0   0        1.0    1.00
4   0   0   1        0.0    0.00

In [41]:
df_matrix.to_csv("Accuracy_Sheet_on_tagged_data_string_match.csv", index = False)